"""services/api/auth/webauthn.py — thin wrappers over py_webauthn.

Backend-spec §8.5.1 + §5.1 contract:

  * Library: ``py_webauthn`` server-side; ``@simplewebauthn/browser`` client.
  * ``attestation = 'none'`` (single-operator; we trust the operator's
    authenticator)
  * ``userVerification = 'required'`` for ALL ceremonies -- registration,
    routine login, AND risk-loosening flows. **LOCKED** per dev-guide §1.5
    -- no ``'preferred'`` fallback anywhere.

py_webauthn returns dataclasses with bytes fields; this module converts to
the JSON-able dicts that the FastAPI response models expect. Helper
``options_to_dict`` round-trips through ``webauthn.options_to_json`` (which
emits a JSON string) then ``json.loads`` -- the canonical way to get
base64url-encoded blobs out of the structs.

Errors from py_webauthn (``InvalidRegistrationResponse``,
``InvalidAuthenticationResponse``) are translated into
``AppError("WEBAUTHN_VERIFY_FAILED", 401)`` by the route handler; this module
just lets them propagate so the route can attach the context it needs.

A05 N/A. A06 enforced (no timestamp fields here). A22 N/A (pure-policy unit
tests via a fake py_webauthn surface in ``tests/unit/test_webauthn.py``).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Final

import structlog
import webauthn
from webauthn.helpers.cose import COSEAlgorithmIdentifier
from webauthn.helpers.structs import (
    AttestationConveyancePreference,
    AuthenticatorSelectionCriteria,
    PublicKeyCredentialDescriptor,
    UserVerificationRequirement,
)

log = structlog.get_logger()


# Algorithm allow-list mirrors the WebAuthn working-group recommendations.
# ES256 first (most authenticators), then RS256 as a fallback, then EdDSA for
# modern keys (Solokeys, OnlyKey). Hardware tokens negotiate the strongest
# they support.
_SUPPORTED_ALGS: Final[list[COSEAlgorithmIdentifier]] = [
    COSEAlgorithmIdentifier.ECDSA_SHA_256,
    COSEAlgorithmIdentifier.EDDSA,
    COSEAlgorithmIdentifier.RSASSA_PKCS1_v1_5_SHA_256,
]

# LOCKED. Constant exported for unit tests to assert the contract.
USER_VERIFICATION_REQUIRED: Final = UserVerificationRequirement.REQUIRED
ATTESTATION_NONE: Final = AttestationConveyancePreference.NONE


@dataclass(frozen=True)
class WebAuthnChallenge:
    """Returned to the frontend; the bytes blob travels alongside as state."""

    options_dict: dict[str, Any]
    challenge_bytes: bytes
    user_id_bytes: bytes | None
    """``user_id`` is only set for registration ceremonies; login ceremonies
    operate on the credential ID alone."""


@dataclass(frozen=True)
class VerifiedRegistration:
    credential_id: bytes
    credential_public_key: bytes
    sign_count: int
    authenticator_attachment: str | None


@dataclass(frozen=True)
class VerifiedAuthentication:
    credential_id: bytes
    new_sign_count: int


def options_to_dict(options: object) -> dict[str, Any]:
    """Convert py_webauthn options struct to a JSON-able dict.

    py_webauthn ships ``options_to_json`` which emits a string with base64url-
    encoded bytes for ``challenge``, ``user.id``, ``allowCredentials[].id``,
    etc. Re-parsing via ``json.loads`` gives us a dict the FastAPI response
    model can serialize.
    """
    raw = webauthn.options_to_json(options)  # type: ignore[arg-type]
    parsed = json.loads(raw)
    if not isinstance(parsed, dict):
        raise RuntimeError(
            f"py_webauthn options_to_json returned non-dict: {type(parsed).__name__}"
        )
    return parsed


def generate_registration_challenge(
    *,
    rp_id: str,
    rp_name: str,
    user_name: str,
    user_display_name: str,
    exclude_credential_ids: list[bytes] | None = None,
) -> WebAuthnChallenge:
    """Build the ``PublicKeyCredentialCreationOptions`` for /register/challenge.

    ``user_id`` is auto-generated by py_webauthn (64 random bytes) when not
    supplied; we let it be auto-generated since the operator's account UUID
    isn't an appropriate WebAuthn user handle (privacy + per-credential
    rotation). The bytes are stashed in the ceremony state and re-asserted
    on verify (py_webauthn re-checks at verification time).
    """
    selection = AuthenticatorSelectionCriteria(
        user_verification=USER_VERIFICATION_REQUIRED,
    )
    exclude = (
        [
            PublicKeyCredentialDescriptor(id=cid, transports=None)
            for cid in (exclude_credential_ids or [])
        ]
        if exclude_credential_ids
        else None
    )
    options = webauthn.generate_registration_options(
        rp_id=rp_id,
        rp_name=rp_name,
        user_name=user_name,
        user_display_name=user_display_name,
        attestation=ATTESTATION_NONE,
        authenticator_selection=selection,
        supported_pub_key_algs=_SUPPORTED_ALGS,
        exclude_credentials=exclude,
    )
    return WebAuthnChallenge(
        options_dict=options_to_dict(options),
        challenge_bytes=options.challenge,
        user_id_bytes=options.user.id,
    )


def verify_registration(
    *,
    credential: dict[str, Any],
    expected_challenge: bytes,
    expected_rp_id: str,
    expected_origin: str,
) -> VerifiedRegistration:
    """Verify the client's response to ``navigator.credentials.create()``.

    ``require_user_verification=True`` enforces the LOCKED ``UV=required``
    contract -- a credential that didn't actually perform user verification
    fails this check and the route returns 401.
    """
    verified = webauthn.verify_registration_response(
        credential=credential,
        expected_challenge=expected_challenge,
        expected_rp_id=expected_rp_id,
        expected_origin=expected_origin,
        require_user_verification=True,
        supported_pub_key_algs=_SUPPORTED_ALGS,
    )
    # py_webauthn exposes ``aaguid``, ``credential_id``, ``credential_public_key``,
    # ``sign_count``, ``credential_type``, ``user_verified``, ``credential_device_type``,
    # ``credential_backed_up``, ``fmt``, ``attestation_object``. Day 21 stores
    # the credential_id + public_key + sign_count; aaguid is informational.
    attachment_value: str | None = None
    attachment = getattr(verified, "credential_device_type", None)
    if attachment is not None:
        # Older py_webauthn versions expose this as an enum; new versions as
        # a string. Coerce to string for the TEXT column.
        attachment_value = attachment.value if hasattr(attachment, "value") else str(attachment)
    return VerifiedRegistration(
        credential_id=verified.credential_id,
        credential_public_key=verified.credential_public_key,
        sign_count=verified.sign_count,
        authenticator_attachment=attachment_value,
    )


def generate_authentication_challenge(
    *,
    rp_id: str,
    allow_credential_ids: list[bytes],
) -> WebAuthnChallenge:
    """Build the ``PublicKeyCredentialRequestOptions`` for /webauthn/challenge."""
    allow = [PublicKeyCredentialDescriptor(id=cid, transports=None) for cid in allow_credential_ids]
    options = webauthn.generate_authentication_options(
        rp_id=rp_id,
        allow_credentials=allow,
        user_verification=USER_VERIFICATION_REQUIRED,
    )
    return WebAuthnChallenge(
        options_dict=options_to_dict(options),
        challenge_bytes=options.challenge,
        user_id_bytes=None,
    )


def verify_authentication(
    *,
    credential: dict[str, Any],
    expected_challenge: bytes,
    expected_rp_id: str,
    expected_origin: str,
    credential_public_key: bytes,
    current_sign_count: int,
) -> VerifiedAuthentication:
    """Verify the client's response to ``navigator.credentials.get()``.

    py_webauthn rejects the verification if the authenticator's ``sign_count``
    did NOT advance past ``current_sign_count`` -- a regressed counter
    signals a cloned credential (or buggy authenticator). Either way we
    refuse the auth and the route returns 401.
    """
    verified = webauthn.verify_authentication_response(
        credential=credential,
        expected_challenge=expected_challenge,
        expected_rp_id=expected_rp_id,
        expected_origin=expected_origin,
        credential_public_key=credential_public_key,
        credential_current_sign_count=current_sign_count,
        require_user_verification=True,
    )
    # py_webauthn exposes ``new_sign_count`` + ``credential_id`` on a successful
    # verification. Per spec, we now persist new_sign_count back to the row.
    return VerifiedAuthentication(
        credential_id=verified.credential_id,
        new_sign_count=verified.new_sign_count,
    )


__all__ = [
    "ATTESTATION_NONE",
    "USER_VERIFICATION_REQUIRED",
    "VerifiedAuthentication",
    "VerifiedRegistration",
    "WebAuthnChallenge",
    "generate_authentication_challenge",
    "generate_registration_challenge",
    "options_to_dict",
    "verify_authentication",
    "verify_registration",
]
