"""services/reconciliation/flex_query_fetcher.py — IBKR FlexQuery web service client.

Pivot-PR-C (post-pivot 2026-05-12). Pulls EOD reconciliation data directly
from IBKR's FlexQuery web service (XML over HTTPS) — replaces the
pre-pivot QC-mediated FlexQuery push (RETIRED; QC algorithm used to
pull FlexQuery + push to ObjectStore for backend to poll).

**A02 BINDS** — `services/reconciliation/**` on forbidden whitelist;
`risk-review-approved` required.

**FlexQuery flow (IBKR's contract):**

  1. Operator pre-creates a FlexQuery template in IBKR portal:
     Reports → Flex Queries → Create. Templates configure which fields
     (positions, cash, trades, dividends, ex-date metadata) are included.
  2. The template gets a numeric ID + a token (auto-generated by IBKR).
  3. Both go into sops: `ibkr.flex_query_id` + `ibkr.flex_query_token`.
  4. To pull: GET `/AccountManagement/FlexWebService/SendRequest?t=<token>&q=<id>&v=3`
     → returns 200 with a XML body containing `<ReferenceCode>` (unique
     per request).
  5. GET `/AccountManagement/FlexWebService/GetStatement?t=<token>&q=<refcode>&v=3`
     → returns 200 with the actual FlexQuery XML report.
  6. Parse the XML into our internal `ReconciliationSnapshot` shape that
     the Day 9 PR #42 pure-policy `plan_reconciliation_check` consumes.

The 2-step pattern is IBKR's design (FlexQuery generation is async on
their side; the SendRequest returns a reference code which the polling
loop redeems for the actual data). Typical wall-clock: 5-30 seconds
between SendRequest + first available GetStatement.

Sample XML root elements parsed:
* `<AccountInformation>` — account_id, currency, type
* `<OpenPositions>` — list of `<OpenPosition>` rows with symbol, qty, cost_basis, value
* `<CashReport>` — currency balances + interest accruals
* `<Trades>` — list of `<Trade>` rows for the day
* `<EquitySummaryByReportDateInBase>` — equity summary anchor

**Pivot-PR-C scope** ships:
* `IbkrFlexQueryClient` httpx-async client with `request_statement()` +
  `poll_statement()` + retry semantics
* XML parser via stdlib `xml.etree.ElementTree` (no external dep)
* `ReconciliationSnapshot` dataclass — the consumable input for the
  Day 9 PR #42 recon planner
* Errors mapped to `FlexQueryFetchError` for downstream classification

**Pivot-PR-C does NOT** wire the fetcher into the recon scheduler or
write reconciliation_breaks rows. That's a follow-up PR (consumes the
snapshot via `plan_reconciliation_check(...)` from `recon.py` + applies
the plan).

A05 enforced (Decimal-as-string at XML→snapshot boundary).
A06 enforced (every datetime tz-aware UTC).
"""

from __future__ import annotations

import asyncio
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from datetime import UTC, date, datetime
from decimal import Decimal
from typing import Final

import httpx
import structlog

log = structlog.get_logger()


_FLEX_BASE_URL: Final[str] = (
    "https://gdcdyn.interactivebrokers.com/AccountManagement/FlexWebService"
)
_FLEX_VERSION: Final[str] = "3"

#: IBKR's FlexQuery generation is async; poll until ready.
_DEFAULT_POLL_MAX_ATTEMPTS: Final[int] = 12  # 12 * 5s = 60s max wait
_DEFAULT_POLL_INTERVAL_SECONDS: Final[float] = 5.0

#: IBKR's "statement not yet ready" response codes (per their docs).
#: Code 1019 = "Statement generation in progress; retry"
#: Code 1020 = "Statement generation queued; retry"
_RETRYABLE_ERROR_CODES: Final[frozenset[int]] = frozenset({1019, 1020})


@dataclass(frozen=True, slots=True)
class FlexPosition:
    """One open-position row from the FlexQuery `OpenPositions` element."""

    account_id: str
    symbol: str  # IBKR's symbol; e.g., "MES" for futures, "TLT" for ETFs
    sec_type: str  # FUT / STK / OPT / CASH
    quantity: Decimal  # signed: positive=long, negative=short
    avg_cost_usd: Decimal
    market_price_usd: Decimal | None
    market_value_usd: Decimal | None
    unrealized_pnl_usd: Decimal | None


@dataclass(frozen=True, slots=True)
class FlexCashBalance:
    """Currency balance from the FlexQuery `CashReport` element."""

    currency: str  # ISO 4217 (typically "USD")
    balance: Decimal
    accrued_interest: Decimal = Decimal(0)


@dataclass(frozen=True, slots=True)
class FlexAccountSummary:
    """Aggregate from `EquitySummaryByReportDateInBase`."""

    account_id: str
    report_date: date
    net_liquidation_usd: Decimal
    cash_usd: Decimal
    stock_market_value_usd: Decimal
    bond_market_value_usd: Decimal
    futures_pnl_usd: Decimal


@dataclass(frozen=True, slots=True)
class ReconciliationSnapshot:
    """Pull-time snapshot consumable by the Day 9 PR #42 recon planner.

    Produced by :func:`parse_flex_xml`; consumed by a follow-up PR that
    calls into ``services.reconciliation.recon.plan_reconciliation_check(...)``.
    """

    pulled_at_utc: datetime
    account_summary: FlexAccountSummary
    positions: tuple[FlexPosition, ...]
    cash_balances: tuple[FlexCashBalance, ...]


class FlexQueryFetchError(Exception):
    """Raised on terminal-failure FlexQuery fetches.

    Reasons:
        * AUTH_INVALID — token rejected (401-equivalent)
        * QUERY_NOT_FOUND — flex_query_id doesn't exist on this account
        * MAX_ATTEMPTS_EXHAUSTED — statement never reached ready state
          after :data:`_DEFAULT_POLL_MAX_ATTEMPTS` polls
        * MALFORMED_XML — parser couldn't extract required elements
        * NETWORK_ERROR — HTTP-level error (timeout, DNS, etc.)
    """

    def __init__(
        self, error_code: str, message: str, details: dict[str, str] | None = None
    ) -> None:
        super().__init__(message)
        self.error_code = error_code
        self.message = message
        self.details = details or {}


def _ts_utc() -> datetime:
    return datetime.now(tz=UTC)


def _parse_decimal(text: str | None, default: Decimal | None = None) -> Decimal | None:
    """Parse XML text → Decimal preserving precision. None on empty/missing."""
    if text is None or text.strip() == "":
        return default
    try:
        return Decimal(text.strip())
    except (ValueError, ArithmeticError):
        return default


def _parse_required_decimal(text: str | None, field_name: str) -> Decimal:
    """Like _parse_decimal but raises if missing/unparseable."""
    val = _parse_decimal(text)
    if val is None:
        raise FlexQueryFetchError(
            error_code="MALFORMED_XML",
            message=f"required field {field_name} missing or unparseable",
        )
    return val


def parse_flex_xml(xml_text: str) -> ReconciliationSnapshot:
    """Parse a FlexQuery XML body into a :class:`ReconciliationSnapshot`.

    IBKR's XML structure is non-trivial; this parser extracts the elements
    we need for reconciliation:
        - `<FlexStatement>` (root container, one per account)
        - `<EquitySummaryByReportDateInBase>` (one row per report date)
        - `<OpenPositions>/<OpenPosition>` (zero+ rows)
        - `<CashReport>/<CashReportCurrency>` (one+ rows per currency)
    """
    try:
        # S314 noqa rationale (applied to the next line): source is IBKR's
        # authenticated FlexQuery API endpoint; auth via sops-encrypted token
        # before any XML touches this parser. Python 3.11+'s xml.etree default
        # config disables external entity resolution.
        root = ET.fromstring(xml_text)  # noqa: S314
    except ET.ParseError as exc:
        raise FlexQueryFetchError(
            error_code="MALFORMED_XML",
            message=f"FlexQuery XML parse failed: {exc}",
        ) from exc

    # Check for IBKR error response (a `<FlexQueryResponse><code>` shape).
    error_code_elem = root.find(".//ErrorCode")
    if error_code_elem is not None:
        msg_elem = root.find(".//ErrorMessage")
        msg = msg_elem.text if msg_elem is not None else "unknown"
        raise FlexQueryFetchError(
            error_code="IBKR_RETURNED_ERROR",
            message=f"IBKR error {error_code_elem.text}: {msg}",
            details={"ibkr_error_code": error_code_elem.text or ""},
        )

    # FlexStatement is the per-account container.
    statement = root.find(".//FlexStatement")
    if statement is None:
        raise FlexQueryFetchError(
            error_code="MALFORMED_XML",
            message="FlexStatement element not found in response",
        )

    account_info = statement.find(".//AccountInformation")
    if account_info is None:
        raise FlexQueryFetchError(
            error_code="MALFORMED_XML",
            message="AccountInformation element not found",
        )
    account_id = account_info.get("accountId", "")

    # EquitySummary — one row per report date; we take the latest.
    equity_summaries = statement.findall(".//EquitySummaryByReportDateInBase")
    if not equity_summaries:
        raise FlexQueryFetchError(
            error_code="MALFORMED_XML",
            message="EquitySummaryByReportDateInBase rows missing",
        )
    latest_summary_elem = equity_summaries[-1]
    report_date_str = latest_summary_elem.get("reportDate", "")
    try:
        report_date = datetime.strptime(report_date_str, "%Y-%m-%d").date()
    except ValueError as exc:
        raise FlexQueryFetchError(
            error_code="MALFORMED_XML",
            message=f"invalid reportDate format: {report_date_str!r}",
        ) from exc

    account_summary = FlexAccountSummary(
        account_id=account_id,
        report_date=report_date,
        net_liquidation_usd=_parse_required_decimal(
            latest_summary_elem.get("total"), "EquitySummary.total"
        ),
        cash_usd=_parse_decimal(latest_summary_elem.get("cash"), default=Decimal(0)) or Decimal(0),
        stock_market_value_usd=_parse_decimal(latest_summary_elem.get("stock"), default=Decimal(0))
        or Decimal(0),
        bond_market_value_usd=_parse_decimal(latest_summary_elem.get("bond"), default=Decimal(0))
        or Decimal(0),
        futures_pnl_usd=_parse_decimal(latest_summary_elem.get("futuresPNL"), default=Decimal(0))
        or Decimal(0),
    )

    # OpenPositions — zero+ rows.
    positions: list[FlexPosition] = []
    for pos_elem in statement.findall(".//OpenPosition"):
        positions.append(
            FlexPosition(
                account_id=account_id,
                symbol=pos_elem.get("symbol", ""),
                sec_type=pos_elem.get("assetCategory", ""),
                quantity=_parse_required_decimal(pos_elem.get("position"), "OpenPosition.position"),
                avg_cost_usd=_parse_required_decimal(
                    pos_elem.get("costBasisPrice"), "OpenPosition.costBasisPrice"
                ),
                market_price_usd=_parse_decimal(pos_elem.get("markPrice")),
                market_value_usd=_parse_decimal(pos_elem.get("positionValue")),
                unrealized_pnl_usd=_parse_decimal(pos_elem.get("fifoPnlUnrealized")),
            )
        )

    # CashReport — one+ rows per currency.
    cash_balances: list[FlexCashBalance] = []
    for cash_elem in statement.findall(".//CashReportCurrency"):
        cash_balances.append(
            FlexCashBalance(
                currency=cash_elem.get("currency", ""),
                balance=_parse_required_decimal(
                    cash_elem.get("endingCash"), "CashReportCurrency.endingCash"
                ),
                accrued_interest=_parse_decimal(
                    cash_elem.get("accruedInterest"), default=Decimal(0)
                )
                or Decimal(0),
            )
        )

    return ReconciliationSnapshot(
        pulled_at_utc=_ts_utc(),
        account_summary=account_summary,
        positions=tuple(positions),
        cash_balances=tuple(cash_balances),
    )


class IbkrFlexQueryClient:
    """Async client for IBKR's FlexQuery web service.

    Constructed once per recon cycle (cheap; no persistent state). The
    operator's sops bundle carries the ``flex_query_id`` + ``flex_query_token``
    pair; these are passed in at construction time.
    """

    def __init__(
        self,
        *,
        flex_query_id: int,
        token: str,
        http_client: httpx.AsyncClient | None = None,
        base_url: str = _FLEX_BASE_URL,
        poll_max_attempts: int = _DEFAULT_POLL_MAX_ATTEMPTS,
        poll_interval_seconds: float = _DEFAULT_POLL_INTERVAL_SECONDS,
    ) -> None:
        if flex_query_id <= 0:
            raise ValueError(f"flex_query_id must be positive, got {flex_query_id}")
        if not token:
            raise ValueError("token must be non-empty")
        self._flex_query_id = flex_query_id
        self._token = token
        self._base_url = base_url.rstrip("/")
        self._poll_max_attempts = poll_max_attempts
        self._poll_interval_seconds = poll_interval_seconds
        self._http_client = http_client

    async def fetch_snapshot(self) -> ReconciliationSnapshot:
        """Two-step fetch: SendRequest → poll → GetStatement → parse.

        Returns a :class:`ReconciliationSnapshot` on success.
        Raises :class:`FlexQueryFetchError` on terminal failure.
        """
        owns_client = self._http_client is None
        client = self._http_client or httpx.AsyncClient(timeout=30.0)
        try:
            ref_code = await self._send_request(client)
            xml_text = await self._poll_for_statement(client, ref_code)
            return parse_flex_xml(xml_text)
        finally:
            if owns_client:
                await client.aclose()

    async def _send_request(self, client: httpx.AsyncClient) -> str:
        url = f"{self._base_url}/SendRequest"
        params = {"t": self._token, "q": str(self._flex_query_id), "v": _FLEX_VERSION}
        try:
            response = await client.get(url, params=params)
        except httpx.HTTPError as exc:
            raise FlexQueryFetchError(
                error_code="NETWORK_ERROR",
                message=f"SendRequest network error: {exc}",
            ) from exc

        if response.status_code == 401 or response.status_code == 403:
            raise FlexQueryFetchError(
                error_code="AUTH_INVALID",
                message=f"FlexQuery auth failed: HTTP {response.status_code}",
            )

        if response.status_code != 200:
            raise FlexQueryFetchError(
                error_code="NETWORK_ERROR",
                message=f"SendRequest returned HTTP {response.status_code}",
            )

        try:
            root = ET.fromstring(response.text)  # noqa: S314 (see parse_flex_xml)
        except ET.ParseError as exc:
            raise FlexQueryFetchError(
                error_code="MALFORMED_XML",
                message=f"SendRequest XML parse failed: {exc}",
            ) from exc

        # Success response: `<FlexStatementResponse><Status>Success</Status><ReferenceCode>...`
        status = root.find(".//Status")
        if status is not None and status.text == "Success":
            ref_code = root.find(".//ReferenceCode")
            if ref_code is not None and ref_code.text:
                return ref_code.text

        # Error response: `<FlexStatementResponse><Status>Fail</Status><ErrorCode>...`
        error_code_elem = root.find(".//ErrorCode")
        error_msg_elem = root.find(".//ErrorMessage")
        msg = error_msg_elem.text if error_msg_elem is not None else "unknown"
        if error_code_elem is not None and error_code_elem.text:
            ibkr_code_text = error_code_elem.text.strip()
            try:
                ibkr_code_int = int(ibkr_code_text)
            except ValueError:
                ibkr_code_int = -1
            if ibkr_code_int == 1003 or ibkr_code_int == 1004:
                raise FlexQueryFetchError(
                    error_code="QUERY_NOT_FOUND",
                    message=f"FlexQuery {self._flex_query_id} not found or token invalid: {msg}",
                    details={"ibkr_error_code": ibkr_code_text},
                )
            raise FlexQueryFetchError(
                error_code="IBKR_RETURNED_ERROR",
                message=f"FlexQuery SendRequest failed: code={ibkr_code_text} msg={msg}",
                details={"ibkr_error_code": ibkr_code_text},
            )

        raise FlexQueryFetchError(
            error_code="MALFORMED_XML",
            message="SendRequest response lacked both Status=Success+ReferenceCode and ErrorCode",
        )

    async def _poll_for_statement(self, client: httpx.AsyncClient, ref_code: str) -> str:
        """Poll GetStatement until ready or :data:`_DEFAULT_POLL_MAX_ATTEMPTS` exhausted."""
        url = f"{self._base_url}/GetStatement"
        params = {"t": self._token, "q": ref_code, "v": _FLEX_VERSION}
        for attempt in range(self._poll_max_attempts):
            try:
                response = await client.get(url, params=params)
            except httpx.HTTPError as exc:
                raise FlexQueryFetchError(
                    error_code="NETWORK_ERROR",
                    message=f"GetStatement network error: {exc}",
                ) from exc

            if response.status_code != 200:
                raise FlexQueryFetchError(
                    error_code="NETWORK_ERROR",
                    message=f"GetStatement returned HTTP {response.status_code}",
                )

            # Check if this is a "not yet ready" response (returns XML with ErrorCode 1019/1020).
            try:
                root = ET.fromstring(response.text)  # noqa: S314 (see parse_flex_xml)
                error_code_elem = root.find(".//ErrorCode")
                if error_code_elem is not None and error_code_elem.text:
                    try:
                        ibkr_code_int = int(error_code_elem.text.strip())
                    except ValueError:
                        ibkr_code_int = -1
                    if ibkr_code_int in _RETRYABLE_ERROR_CODES:
                        log.info(
                            "flex_query_poll_retry",
                            attempt=attempt + 1,
                            max_attempts=self._poll_max_attempts,
                            ibkr_code=ibkr_code_int,
                        )
                        await asyncio.sleep(self._poll_interval_seconds)
                        continue
                    # Non-retryable error
                    error_msg_elem = root.find(".//ErrorMessage")
                    msg = error_msg_elem.text if error_msg_elem is not None else "unknown"
                    raise FlexQueryFetchError(
                        error_code="IBKR_RETURNED_ERROR",
                        message=f"GetStatement failed: code={ibkr_code_int} msg={msg}",
                        details={"ibkr_error_code": str(ibkr_code_int)},
                    )
                # No error element: assume this is the actual statement.
                return response.text
            except ET.ParseError as exc:
                raise FlexQueryFetchError(
                    error_code="MALFORMED_XML",
                    message=f"GetStatement XML parse failed: {exc}",
                ) from exc

        raise FlexQueryFetchError(
            error_code="MAX_ATTEMPTS_EXHAUSTED",
            message=(
                f"FlexQuery statement never reached ready state after "
                f"{self._poll_max_attempts} polls "
                f"({self._poll_max_attempts * self._poll_interval_seconds:.0f}s total)"
            ),
        )


__all__ = [
    "FlexAccountSummary",
    "FlexCashBalance",
    "FlexPosition",
    "FlexQueryFetchError",
    "IbkrFlexQueryClient",
    "ReconciliationSnapshot",
    "parse_flex_xml",
]
